<?php
$username="root";
$password="root";
$database="sever";
$tableAccount="account2";
$tableCallLog="call_logs2";
$tableDangerArea="danger_area2";
$tableParameters="parameters2";
$tablePosition="position2";
$tableSms="sms2";
?>